# File: .github/workflows/publish.yml
name: publish-to-github-pages
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4

      - name: Build with Next.js 🏗️
        run: npx next build
        env:
          NEXT_PUBLIC_DATABASE_API_KEY: ${{ secrets.NEXT_PUBLIC_DATABASE_API_KEY }}
          NEXT_PUBLIC_DATABASE_NAME: ${{ secrets.NEXT_PUBLIC_DATABASE_NAME }}
          NEXT_PUBLIC_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_DATABASE_ID }}
          NEXT_PUBLIC_DATABASE_SERVICE_NAME: ${{ secrets.NEXT_PUBLIC_DATABASE_SERVICE_NAME }}
          NEXT_PUBLIC_DATABASE_BILL_COLLECTION: ${{ secrets.NEXT_PUBLIC_DATABASE_BILL_COLLECTION }}
          NEXT_PUBLIC_DATABASE_BILL_CONTRIBUTION_COLLECTION: ${{ secrets.NEXT_PUBLIC_DATABASE_BILL_CONTRIBUTION_COLLECTION }}
          NEXT_PUBLIC_USER_PASSWORD: ${{ secrets.NEXT_PUBLIC_USER_PASSWORD }}
          NEXT_PUBLIC_JWT_SECRET: ${{ secrets.NEXT_PUBLIC_JWT_SECRET }}

      - name: Upload artifact 📡
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
    # steps:
    #   - name: Publish to GitHub Pages 🚀
    #     id: deployment
    #     run: node .next/standalone/server.js